// Generated by `make build contracts` (packages/contracts/scripts/generate-abi.py).
// Do not edit the .json files by hand -- CI's `make contract abi-check` fails if they
// drift from the contract sources. The backend indexer reads its event definitions
// from here rather than hand-transcribing them
// (apps/backend/src/services/indexer-abi-events.ts).
import abi from './TaskMarket.json';
import epochBudgetAbi from './EpochBudget.json';
import rewardVaultAbi from './RewardVault.json';
import taskTokenRewardHookAbi from './TaskTokenRewardHook.json';

export const TaskMarketABI = abi;
export const EpochBudgetABI = epochBudgetAbi;
export const RewardVaultABI = rewardVaultAbi;
export const TaskTokenRewardHookABI = taskTokenRewardHookAbi;
