import { Command } from 'commander';
import { createCmd } from './create.js';
import { listCmd } from './search.js';
import { getCmd } from './get.js';
import { submitCmd } from './submit.js';
import { acceptCmd } from './accept.js';
import { acceptSubmissionsCmd } from './accept-submissions.js';
import { rateCmd } from './rate.js';
import { claimCmd } from './claim.js';
import { pitchCmd } from './pitch.js';
import { selectWorkerCmd } from './select-worker.js';
import { proofCmd } from './proof.js';
import { bidCmd } from './bid.js';
import { auctionAcceptCmd } from './auction-accept.js';
import { submissionsCmd } from './submissions.js';
import { selectWinnerCmd } from './select-winner.js';
import { downloadCmd } from './download.js';
import { cancelCmd } from './cancel.js';
import { refundExpiredCmd } from './refund-expired.js';
import { updateCmd } from './update.js';
import { forfeitCmd } from './forfeit.js';
import { evaluateCmd } from './evaluate.js';
import { appealCmd } from './appeal.js';
import { evaluatorTimeoutCmd } from './evaluator-timeout.js';
import { finalizeVerdictCmd } from './finalize-verdict.js';
import { resolveDisputeCmd } from './resolve-dispute.js';

export const taskCommand = new Command('task').description('Manage tasks');

taskCommand.addCommand(createCmd);
taskCommand.addCommand(listCmd);
taskCommand.addCommand(getCmd);
taskCommand.addCommand(submitCmd);
taskCommand.addCommand(acceptCmd);
taskCommand.addCommand(acceptSubmissionsCmd);
taskCommand.addCommand(rateCmd);
taskCommand.addCommand(claimCmd);
taskCommand.addCommand(pitchCmd);
taskCommand.addCommand(selectWorkerCmd);
taskCommand.addCommand(proofCmd);
taskCommand.addCommand(bidCmd);
taskCommand.addCommand(auctionAcceptCmd);
taskCommand.addCommand(submissionsCmd);
taskCommand.addCommand(selectWinnerCmd);
taskCommand.addCommand(downloadCmd);
taskCommand.addCommand(cancelCmd);
taskCommand.addCommand(refundExpiredCmd);
taskCommand.addCommand(updateCmd);
taskCommand.addCommand(forfeitCmd);
taskCommand.addCommand(evaluateCmd);
taskCommand.addCommand(appealCmd);
taskCommand.addCommand(evaluatorTimeoutCmd);
taskCommand.addCommand(finalizeVerdictCmd);
taskCommand.addCommand(resolveDisputeCmd);
