#!/usr/bin/env bash
# Sandbox setup for cloud coding agents (Claude Code cloud, Codex cloud).
# Brings up the full Taskmarket stack inside a single Linux VM/container:
# toolchain, native Postgres (no Docker), a local Anvil chain, contracts
# deployed to it, and a .env the Makefile's ENV_LOADER picks up -- so
# `make smoke <mode>` works entirely on localhost afterwards.
#
# STATUS: first draft, not yet executed inside a real vendor sandbox.
# Expected first-run friction: native Postgres setup on the vendor image,
# git submodules, and the full backend env var set (see .env.example for
# anything the backend still complains about). See the "Tier-2 setup"
# section of docs/specs/agentic-development-factory-rfc.md.
#
# All keys below are Anvil's well-known, pre-funded default dev accounts.
# They are public knowledge and safe ONLY because this chain never leaves
# the sandbox. Never use them against a real network.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

ANVIL_RPC_URL="http://127.0.0.1:8545"
DB_USER="taskmarket"
DB_PASSWORD="taskmarket"
DB_NAME="taskmarket"

# Anvil default accounts #0..#5 (deterministic, pre-funded with 10k ETH each)
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
SERVER_KEY="0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
REQUESTER_KEY="0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"
WORKER_KEY="0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"
WORKER_B_KEY="0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a"
EVALUATOR_KEY="0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba"
DEPLOYER_ADDRESS="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

echo "==> [1/7] Toolchain (Node, pnpm, Foundry)"
if ! command -v pnpm > /dev/null 2>&1; then
  npm install -g pnpm@8.15.0
fi
if ! command -v forge > /dev/null 2>&1; then
  curl -L https://foundry.paradigm.xyz | bash
  export PATH="$HOME/.foundry/bin:$PATH"
  foundryup
fi

echo "==> [2/7] Git submodules (contracts dependencies)"
git submodule update --init --recursive

echo "==> [3/7] Native Postgres (cloud sandboxes have no Docker)"
if ! command -v pg_isready > /dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -qq && sudo apt-get install -y -qq postgresql
fi
sudo service postgresql start || sudo pg_ctlcluster "$(ls /etc/postgresql | head -1)" main start
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD' SUPERUSER"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 \
  || sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"

echo "==> [4/7] Workspace dependencies"
make install

echo "==> [5/7] Local Anvil chain"
if ! curl -sf -X POST "$ANVIL_RPC_URL" -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' > /dev/null 2>&1; then
  nohup anvil --host 127.0.0.1 --port 8545 > /tmp/anvil.log 2>&1 &
  for _ in $(seq 1 30); do
    curl -sf -X POST "$ANVIL_RPC_URL" -H 'Content-Type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' > /dev/null 2>&1 && break
    sleep 1
  done
fi

echo "==> [6/7] Deploy mock USDC + diamond to local Anvil"
cd packages/contracts
FORGE_DEV_PRIVATE_KEY="$DEPLOYER_KEY" \
  forge script script/DeployMockUSDCPreview.s.sol:DeployMockUSDCPreview \
  --rpc-url "$ANVIL_RPC_URL" --broadcast 2>&1 | tee /tmp/usdc-deploy.log
USDC_ADDRESS="$(grep 'Mock USDC deployed at:' /tmp/usdc-deploy.log | awk '{print $NF}')"
cd "$REPO_ROOT"

cat > .env << EOF
# Generated by scripts/cloud-env-setup.sh -- local sandbox stack.
# Anvil default dev keys: public knowledge, sandbox-only, never real networks.
NODE_ENV=development
DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@localhost:5432/$DB_NAME
FORGE_ANVIL_RPC_URL=$ANVIL_RPC_URL
FORGE_DEV_PRIVATE_KEY=$DEPLOYER_KEY
FORGE_USDC_TOKEN_ADDRESS=$USDC_ADDRESS
FORGE_FEE_RECIPIENT_ADDRESS=$DEPLOYER_ADDRESS
FORGE_DEFAULT_PLATFORM_FEE_BPS=500
SERVER_PRIVATE_KEY=$SERVER_KEY
DEV_PRIVATE_KEY=$DEPLOYER_KEY
REQUESTER_PRIVATE_KEY=$REQUESTER_KEY
WORKER_PRIVATE_KEY=$WORKER_KEY
WORKER_B_PRIVATE_KEY=$WORKER_B_KEY
EVALUATOR_PRIVATE_KEY=$EVALUATOR_KEY
EOF

make deploy preview 2>&1 | tee /tmp/diamond-deploy.log
DIAMOND_ADDRESS="$(grep 'Diamond deployed at:' /tmp/diamond-deploy.log | awk '{print $NF}')"
echo "FORGE_DIAMOND_ADDRESS=$DIAMOND_ADDRESS" >> .env

echo "==> [7/7] Done"
echo "Diamond:   $DIAMOND_ADDRESS"
echo "Mock USDC: $USDC_ADDRESS"
echo "Next: start the backend (make dev, or the backend app directly -- migrations"
echo "run on boot), then run smoke tests: make smoke <mode>"
